### ISSUE TITLE
Síntesis-javiern-778 

### ISSUE THREAD

**Issue by javiern-778** [SistemasTecTlaxiaco/actividad-3-sintesis-javiern-778#2]
[ELEMENTOS IMPORTANTES DE LA GESTIÓN DE PROYECTOS DE SOFTWARE.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-sintesis-javiern-778/files/9447595/ELEMENTOS.IMPORTANTES.DE.LA.GESTION.DE.PROYECTOS.DE.SOFTWARE.pdf)

**Comment by ArturoAngonJose** [comment]
Calificación: 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
